language: bash
sudo: required
env:
  - ARCH=x86
  - ARCH=arm CHROOT_ARCH=armel
  - ARCH=arm CHROOT_ARCH=armhf
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y debootstrap qemu-user-static binfmt-support sbuild
script:
  - "bash -ex .travis-ci-test-install-tor-packages.sh"
  - "bash -ex .travis-ci-test-install-tor-packages-proposed-updates-repo.sh"
